openapi: 3.0.0
info:
  title: Users API
  version: 1.0.0
  description: API para gestionar usuarios
paths:
  /api/users:
    get:
      summary: Obtener todos los usuarios
      tags: [Users]
      responses:
        '200':
          description: Lista de usuarios
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'

  /api/users/{uid}:
    get:
      summary: Obtener un usuario por ID
      tags: [Users]
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    $ref: '#/components/schemas/User'
        '404':
          description: Usuario no encontrado

    put:
      summary: Actualizar un usuario
      tags: [Users]
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: Usuario actualizado
        '404':
          description: Usuario no encontrado

    delete:
      summary: Eliminar un usuario
      tags: [Users]
      parameters:
        - name: uid
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Usuario eliminado

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          example: 60d21b4667d0d8992e610c85
        first_name:
          type: string
          example: Juan
        last_name:
          type: string
          example: Pérez
        email:
          type: string
          example: juan.perez@example.com
        password:
          type: string
          example: contrasena123
        role:
          type: string
          example: user
        pets:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
                example: 60d21b8667d0d8992e610c87
